name: '_just'
description: 'A GitHub Action to modify and override your Next.js site on GitHub Pages.'
author: 'JustDeveloper1'
branding:
  icon: 'edit'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - run: |
        bash prepare_deployment.sh
      shell: bash
    - run: |
        bash create_api_endpoints.sh
      shell: bash
    - run: |
        bash modify_deployment.sh
      shell: bash
    - run: |
        bash override_deployment.sh
      shell: bash
