name: Test website

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-test-website
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate with _just
        uses: js-just/_just@main
        with:
          path: website
  commit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Commit
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: "website"
          destination-github-username: js-just
          destination-repository-name: test
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}